const actionTypes = <const>{
  LOGIN_AUTH_REQUEST: "LOGIN_AUTH_REQUEST",
  LOGIN_AUTH_SUCCESS: "LOGIN_AUTH_SUCCESS",
  LOGIN_AUTH_FAILURE: "LOGIN_AUTH_FAILURE",
  SIGN_UP_AUTH_REQUEST: "SIGN_UP_AUTH_REQUEST",
  SIGN_UP_AUTH_SUCCESS: "SIGN_UP_AUTH_SUCCESS",
  SIGN_UP_AUTH_FAILURE: "SIGN_UP_AUTH_FAILURE",
  UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST",
  UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS",
  UPDATE_USER_INFO_FAILURE: "UPDATE_USER_INFO_FAILURE",
  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",
  SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
};

export default actionTypes;
