const actionTypes = <const>{
  LOGIN_AUTH_REQUEST: "LOGIN_AUTH_REQUEST",
  LOGIN_AUTH_SUCCESS: "LOGIN_AUTH_SUCCESS",
  LOGIN_AUTH_FAILURE: "LOGIN_AUTH_FAILURE",
  SIGN_UP_AUTH_REQUEST: "SIGN_UP_AUTH_REQUEST",
  SIGN_UP_AUTH_SUCCESS: "SIGN_UP_AUTH_SUCCESS",
  SIGN_UP_AUTH_FAILURE: "SIGN_UP_AUTH_FAILURE",
};

export default actionTypes;
