const actionTypes = <const>{
  LOGIN_AUTH_REQUEST: "LOGIN_AUTH_REQUEST",
  LOGIN_AUTH_SUCCESS: "LOGIN_AUTH_SUCCESS",
  LOGIN_AUTH_FAILURE: "LOGIN_AUTH_FAILURE",
  SIGN_UP_AUTH_REQUEST: "SIGN_UP_AUTH_REQUEST",
  SIGN_UP_AUTH_SUCCESS: "SIGN_UP_AUTH_SUCCESS",
  SIGN_UP_AUTH_FAILURE: "SIGN_UP_AUTH_FAILURE",
  UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST",
  UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS",
  UPDATE_USER_INFO_FAILURE: "UPDATE_USER_INFO_FAILURE",
  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",
  SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  USER_LOGIN_STATUS_SUCCESS: "USER_LOGIN_STATUS_SUCCESS",
  USER_LOGIN_STATUS_FAILURE: "USER_LOGIN_STATUS_FAILURE",

  ADD_EXPENSE_REQUEST: "ADD_EXPENSE_REQUEST",
  ADD_EXPENSE_SUCCESS: "ADD_EXPENSE_SUCCESS",
  ADD_EXPENSE_FAILURE: "ADD_EXPENSE_FAILURE",

  ADD_EXPENSE_FOR_UNVERIFIED_REQUEST: "ADD_EXPENSE_FOR_UNVERIFIED_REQUEST",
  ADD_EXPENSE_FOR_UNVERIFIED_SUCCESS: "ADD_EXPENSE_FOR_UNVERIFIED_SUCCESS",
  ADD_EXPENSE_FOR_UNVERIFIED_FAILURE: "ADD_EXPENSE_FOR_UNVERIFIED_FAILURE",

  SETTLE_EXPENSE_REQUEST: "SETTLE_EXPENSE_REQUEST",
  SETTLE_EXPENSE_SUCCESS: "SETTLE_EXPENSE_SUCCESS",
  SETTLE_EXPENSE_FAILURE: "SETTLE_EXPENSE_FAILURE",

  SETTLE_EXPENSE_FOR_UNVERIFIED_REQUEST:
    "SETTLE_EXPENSE_FOR_UNVERIFIED_REQUEST",
  SETTLE_EXPENSE_FOR_UNVERIFIED_SUCCESS:
    "SETTLE_EXPENSE_FOR_UNVERIFIED_SUCCESS",
  SETTLE_EXPENSE_FOR_UNVERIFIED_FAILURE:
    "SETTLE_EXPENSE_FOR_UNVERIFIED_FAILURE",

  SETTLE_EXPENSE_ALL_REQUEST: "SETTLE_EXPENSE_ALL_REQUEST",
  SETTLE_EXPENSE_ALL_SUCCESS: "SETTLE_EXPENSE_ALL_SUCCESS",
  SETTLE_EXPENSE_ALL_FAILURE: "SETTLE_EXPENSE_ALL_FAILURE",

  SETTLE_EXPENSE_ALL_FOR_UNVERIFIED_REQUEST:
    "SETTLE_EXPENSE_ALL_FOR_UNVERIFIED_REQUEST",
  SETTLE_EXPENSE_ALL_FOR_UNVERIFIED_SUCCESS:
    "SETTLE_EXPENSE_ALL_FOR_UNVERIFIED_SUCCESS",
  SETTLE_EXPENSE_ALL_FOR_UNVERIFIED_FAILURE:
    "SETTLE_EXPENSE_ALL_FOR_UNVERIFIED_FAILURE",

  CHECK_USER_REQUEST: "CHECK_USER_REQUEST",
  CHECK_USER_SUCCESS: "CHECK_USER_SUCCESS",
  CHECK_USER_FAILURE: "CHECK_USER_FAILURE",

  ADD_FRIEND_EMAIL_REQUEST: "ADD_FRIEND_EMAIL_REQUEST",
  ADD_FRIEND_EMAIL_SUCCESS: "ADD_FRIEND_EMAIL_SUCCESS",
  ADD_FRIEND_EMAIL_FAILURE: "ADD_FRIEND_EMAIL_FAILURE",

  GET_USER_FRIENDS_REQUEST: "GET_USER_FRIENDS_REQUEST",
  GET_USER_FRIENDS_SUCCESS: "GET_USER_FRIENDS_SUCCESS",
  GET_USER_FRIENDS_FAILURE: "GET_USER_FRIENDS_FAILURE",

  ADD_FRIEND_USING_NAME_REQUEST: "ADD_FRIEND_USING_NAME_REQUEST",
  ADD_FRIEND_USING_NAME_SUCCESS: "ADD_FRIEND_USING_NAME_SUCCESS",
  ADD_FRIEND_USING_NAME_FAILURE: "ADD_FRIEND_USING_NAME_FAILURE",

  SHOW_ERROR_REQUEST: "SHOW_ERROR_REQUEST",
  SHOW_ERROR_SUCCESS: "SHOW_ERROR_SUCCESS",
  SHOW_ERROR_FAILURE: "SHOW_ERROR_FAILURE",

  HIDE_ERROR_REQUEST: "HIDE_ERROR_REQUEST",
  HIDE_ERROR_SUCCESS: "HIDE_ERROR_SUCCESS",
  HIDE_ERROR_FAILURE: "HIDE_ERROR_FAILURE",

  LOADER_REQUEST: "LOADER_REQUEST",
  LOADER_SUCCESS: "LOADER_SUCCESS",
  LOADER_FAILURE: "LOADER_FAILURE",
};

export default actionTypes;
